check shell command

diff --git a/.github/workflows/shell-option.yml b/.github/workflows/shell-option.yml
--- a/.github/workflows/shell-option.yml
+++ b/.github/workflows/shell-option.yml
@@ -29,6 +29,7 @@ jobs:
       - name: when only `bash` specified
         run: |
           echo "shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}"
+          set -o
         shell: bash
 
       # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
@@ -38,3 +39,11 @@ jobs:
           # This command fails
           # diff <(echo hoge) <(echo hogee) > hoge
         shell: bash {0}
+
+      - name: Explicitly specify the errexit option [not working as expected]
+        run: |
+          set -o | grep errexit
+          diff <(echo hoge) <(echo hogee)
+          # This command still fails
+          # diff <(echo hoge) <(echo hogee) > hoge
+        shell: bash +e {0}
